name: CaluculateCovidMetrics

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Step 1 - Create a temporary artifact downloads folder
            run: mkdir /home/runner/work/Covid19Cases/Covid19Cases/downloads
            working-directory: ./downloads
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python need
          - name: Install Python dependencies
            run: |
                python -m pip install pandas
                
          - name: execute py script # run the run.py to get the latest data
            run: |
              python main.py
          - uses: actions/upload-artifact@v3
            with:
              name: Report
              path: /home/runner/work/Covid19Cases/Covid19Cases/downloads
